DOI-ONRR/blog-nrrd

src/pages/6-lessons/index.md

Fixes #46 
[Preview](https://dev-blog-nrrd.app.cloud.gov/6-lessons/)
Changes in this PR
- Add blog post about lessons from my time as product manager

Add lessons blog

---

src/templates/blog-list.js

fixes #62
[:sunglasses: PREVIEW](https://dev-blog-nrrd.app.cloud.gov/)
Next and previous now work.

Fixed bug with next

---

src/pages/contacts/index.md
src/pages/homepage-graphic/index.md

[Contacts](https://dev-blog-nrrd.app.cloud.gov/contacts/)
[Homepage graphic](https://dev-blog-nrrd.app.cloud.gov/homepage-graphic/)

Updates blog post dates

---

src/pages/accessibility/index.md

Fixes #86
[Preview](https://dev-blog-nrrd.app.cloud.gov/accessibility/)

Accessibility refs

---

src/pages/accessibility/index.md

Fixes link to our wiki.
[Preview](https://dev-blog-nrrd.app.cloud.gov/accessibility/)

Fixes wiki link

---

src/data/author.yaml
src/pages/transition-to-management/index.md

[Preview](https://dev-blog-nrrd.app.cloud.gov/transition-to-management/)

Stepping out of my comfort zone – into management   

---

src/pages/beyond-auto/index.md

@Maroyafaied It didn't have the updates when I went to edit dev, so edited the date in my original branch.
https://dev-blog-nrrd.app.cloud.gov/beyond-auto/

Updates date

---

src/pages/plain-language/index.md

Dev to Master Indian language disclaimer

---

src/templates/blog-list.js

[Preview](https://dev-blog-nrrd.app.cloud.gov/[FOLDER NAME]/)

2661-dap-code-include-agency: Updates agency and subagency

---

src/templates/blog-list.js

[Preview](https://dev-blog-nrrd.app.cloud.gov/[FOLDER NAME]/)

Merge dev to master

---

src/templates/blog-list.js

[Preview](https://dev-blog-nrrd.app.cloud.gov/[FOLDER NAME]/)

2661-dap-code-include-agency: Adds script tag attributes.

---

src/components/footer.js

[Preview](https://dev-blog-nrrd.app.cloud.gov/newaddress/)

update address to Denver's office

---

src/components/footer.js
src/components/layout.js
src/pages/trusted-tester/index.md

[Preview](https://dev-blog-nrrd.app.cloud.gov/)

change heading from DOI to ONRR

---

gatsby-config.js
package-lock.json
package.json
src/templates/blog-list.js
src/templates/blog-post.js

- Implements GTM via gatsby-plugin-google-tagmanager
- Removes legacy DAP GA implementation

Implement GTM

---

src/components/footer.js

[Preview](https://dev-blog-nrrd.app.cloud.gov/)
- Added a link to ONRR's accessibility statement in the footer

accessibility-footer

---

gatsby-config.js

Fixes #314 
[Preview](https://dev-blog-nrrd.app.cloud.gov/rss.xml)

Enable RSS feed

---

src/components/footer.js
src/pages/user-research-consent/index.md

[Preview](https://dev-blog-nrrd.app.cloud.gov/user_research_edit/)

minor edit to blog post and footer

---

src/pages/user-research-consent/index.md

Reported by a reader - added a ' to it's in How it's going  
[Preview](https://dev-blog-nrrd.app.cloud.gov/userresearchedits2/)

minor edit to sub heading

---

src/components/footer.js
src/pages/user-research-consent/index.md

Reader reported typo
[Preview](https://dev-blog-nrrd.app.cloud.gov/user-research-consent/)

Dev-->Master User Research Agreement edit

---

src/components/footer.js

[Preview](https://dev-blog-nrrd.app.cloud.gov/)

fix-github-link

---

src/pages/Publishing-Federal-Sales-Data/index.md

[Preview](https://dev-blog-nrrd.app.cloud.gov/UpdateFedSales/)

Fixes to Federal Sales blog

---

.circleci/config.yml

This PR fixes the analytics issue in prod.

445: Adds contexts to prod build (#446)

---

src/data/author.yaml
src/pages/508-Study/index.md
src/pages/accessibility/index.md
src/pages/agile/index.md
src/pages/becoming-a-product-manager/index.md
src/pages/building-technical-with-team-members/index.md
src/pages/content-design-blog-authors/index.md
src/pages/homepage-revamp-part-two/index.md
src/pages/homepage-revamp/index.md
src/pages/making-tough-content-choices/index.md
src/pages/metrics-and-policy/index.md
src/pages/metrics/index.md
src/pages/remote-design-studio/index.md
src/pages/shaping/index.md

[Preview](https://dev-blog-nrrd.app.cloud.gov/Updates/)

Blog updates

---

src/pages/plain-language-accessibility/index.md

[Preview](https://dev-blog-nrrd.app.cloud.gov/)

language-fix
